### ISSUE TITLE
Rainbow Colors

### ISSUE THREAD

**Issue by rms1000watt** [owenthereal/ccat#56]
Rainbow colors are nice to have like: [lolcat](https://github.com/busyloop/lolcat)

Lolcat's deficit is handling utf8, which Golang handles gracefully. This would be great to have in `ccat` so I can move all my monitoring/uptime scripts from `lolcat` to `ccat`.

**Comment by jingweno** [comment]
@rms1000watt I think you could customize colors with `ccat` now: https://github.com/jingweno/ccat#usage, e.g., ` ccat -G String="_darkblue_" -G Plaintext="darkred" FILE`. This is a list of constructs you could customize color for: https://github.com/jingweno/ccat/blob/master/printer.go#L13-L24. And this is a list of predefined named colors: https://github.com/jingweno/ccat/blob/master/color.go#L45-L65. The format of defining it is `ccat -G CONSTRUCT1=COLOR1 -G CONSTRUCT2=COLOR2`. You then alias your `ccat` line like this in your source file: `alias ccat=ccat -G CONSTRUCT1=COLOR1 -G CONSTRUCT2=COLOR2` to provide a shortcut.
